In [3]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

wine = load_wine()
wine_data = wine.data
wine_target = wine.target
df_wine =pd.DataFrame(data = wine_data, columns = wine.feature_names)
df_target =pd.DataFrame(data = wine_target, columns = ['target'])
df = pd.concat([df_wine, df_target], axis=1)

In [4]:
X = df.iloc[:,0:13].values
y = df.iloc[:,13].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [5]:
from keras.layers import Input, Dense
from keras.models import Model
from keras.optimizers import SGD, Adam

# 입력 레이어 정의
inputs = Input(shape=(13,))

# 모델 구조 정의
x = Dense(10, activation='relu')(inputs)
x2 = Dense(8, activation='relu')(x)
x3 = Dense(6, activation='relu')(x2)
outputs = Dense(3, activation='softmax')(x3)

# 모델 정의
model = Model(inputs=inputs, outputs=outputs)

# 모델 컴파일
model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

# 모델 요약 출력
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 13)]              0         
                                                                 
 dense (Dense)               (None, 10)                140       
                                                                 
 dense_1 (Dense)             (None, 8)                 88        
                                                                 
 dense_2 (Dense)             (None, 6)                 54        
                                                                 
 dense_3 (Dense)             (None, 3)                 21        
                                                                 
Total params: 303
Trainable params: 303
Non-trainable params: 0
_________________________________________________________________


C:\Users\a\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [6]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 1s 60ms/step - loss: 21.9200 - accuracy: 0.2746 - val_loss: 1.4353 - val_accuracy: 0.3889
Epoch 2/100
5/5 [==============================] - 0s 11ms/step - loss: 1.2261 - accuracy: 0.4648 - val_loss: 0.9216 - val_accuracy: 0.7500
Epoch 3/100
5/5 [==============================] - 0s 11ms/step - loss: 1.1055 - accuracy: 0.4507 - val_loss: 1.0002 - val_accuracy: 0.4444
Epoch 4/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0431 - accuracy: 0.5070 - val_loss: 0.9439 - val_accuracy: 0.6944
Epoch 5/100
5/5 [==============================] - 0s 10ms/step - loss: 0.9487 - accuracy: 0.6831 - val_loss: 0.8352 - val_accuracy: 0.7500
Epoch 6/100
5/5 [==============================] - 0s 11ms/step - loss: 0.8882 - accuracy: 0.5845 - val_loss: 0.7400 - val_accuracy: 0.6667
Epoch 7/100
5/5 [==============================] - 0s 11ms/step - loss: 0.8492 - accuracy: 0.5845 - val_loss: 0.7100 - val_accuracy: 0.7778
Epoch 8/100
5/5 [==

In [7]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      0.79      0.88        14
           1       0.80      1.00      0.89        16
           2       0.60      0.50      0.55         6

    accuracy                           0.83        36
   macro avg       0.80      0.76      0.77        36
weighted avg       0.84      0.83      0.83        36

[[11  1  2]
 [ 0 16  0]
 [ 0  3  3]]
