In [30]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

wine = load_wine()
wine_data = wine.data
wine_target = wine.target
df_wine =pd.DataFrame(data = wine_data, columns = wine.feature_names)
df_target =pd.DataFrame(data = wine_target, columns = ['target'])
df_wine.shape

(178, 13)

In [31]:
df_target.shape

(178, 1)

In [32]:
df = pd.concat([df_wine, df_target], axis=1)

In [33]:
X = df.iloc[:,0:13].values
y = df.iloc[:,13].values

from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values


from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [34]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam

model = Sequential()
#softmax, tanh, relu
model.add(Dense(50,input_shape=(13,),activation='relu'))
model.add(Dense(30,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.003),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 50)                700       
                                                                 
 dense_5 (Dense)             (None, 30)                1530      
                                                                 
 dense_6 (Dense)             (None, 20)                620       
                                                                 
 dense_7 (Dense)             (None, 3)                 63        
                                                                 
Total params: 2,913
Trainable params: 2,913
Non-trainable params: 0
_________________________________________________________________


C:\Users\a\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [35]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
5/5 [==============================] - 1s 49ms/step - loss: 13.6093 - accuracy: 0.3662 - val_loss: 9.1389 - val_accuracy: 0.3889
Epoch 2/100
5/5 [==============================] - 0s 8ms/step - loss: 7.7026 - accuracy: 0.2887 - val_loss: 4.4318 - val_accuracy: 0.4722
Epoch 3/100
5/5 [==============================] - 0s 9ms/step - loss: 4.8474 - accuracy: 0.4225 - val_loss: 3.5663 - val_accuracy: 0.4444
Epoch 4/100
5/5 [==============================] - 0s 7ms/step - loss: 4.2277 - accuracy: 0.3239 - val_loss: 1.6675 - val_accuracy: 0.3056
Epoch 5/100
5/5 [==============================] - 0s 8ms/step - loss: 2.5307 - accuracy: 0.5423 - val_loss: 2.1310 - val_accuracy: 0.7500
Epoch 6/100
5/5 [==============================] - 0s 8ms/step - loss: 2.8558 - accuracy: 0.6127 - val_loss: 2.5733 - val_accuracy: 0.3333
Epoch 7/100
5/5 [==============================] - 0s 7ms/step - loss: 2.0002 - accuracy: 0.5070 - val_loss: 1.3247 - val_accuracy: 0.6944
Epoch 8/100
5/5 [========

In [36]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      0.93      0.96        14
           1       0.94      0.94      0.94        16
           2       0.86      1.00      0.92         6

    accuracy                           0.94        36
   macro avg       0.93      0.96      0.94        36
weighted avg       0.95      0.94      0.94        36

[[13  1  0]
 [ 0 15  1]
 [ 0  0  6]]
