In [23]:
import pandas as pd
import numpy as np

df= pd.read_csv("C:/Users/a/Downloads/Compressed/iris/iris.data")
features = "sepal_length", "sepal_width", "petal_length", "petal_width", "class"
df.columns = features
df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

In [24]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["class"] = le.fit_transform(df["class"])

In [25]:
X = df.drop("class", axis = 1)

y = df["class"]

In [26]:
from sklearn.model_selection import train_test_split



X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=42)



from sklearn.linear_model import LinearRegression



model = LinearRegression()

model.fit(X_train, y_train)



from sklearn.metrics import mean_squared_error



ly_preds = model.predict(X_test)

mse = np.sqrt(mean_squared_error(ly_preds, y_test))

print('평균제곱근오차', mse)

평균제곱근오차 0.24361038093636314


In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state = 0)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.8947368421052632
[[15  0  0]
 [ 0  8  3]
 [ 0  1 11]]
